[[session]]
name = "misc"
path = "~/Developer"

[[session]]
name = "dotfiles"
path = "~/.dotfiles"

[[session]]
name = "qmk"
path = "~/qmk_userspace"

[[session]]
name = "wking"
path = "~/Developer/projects/wking"

[[session]]
name = "madeforme"
path = "~/Developer/laravel/madeforme"

[[session]]
name = "bridge-frontend"
path = "~/Developer/crunchy/bridge-frontend"

[[session]]
name = "crunchy-www"
path = "~/Developer/crunchy/crunchy-www/"

[[session]]
name = "crunchy-docs"
path = "~/Developer/crunchy/crunchy-docs/"

[[session]]
name = "crunchy-cpk"
path = "~/Developer/crunchy/crunchy-postgres-for-kubernetes-docs"

[[session]]
name = "crunchy-automation"
path = "~/Developer/crunchy/crunchy-postgres-automation-docs"

[[session]]
name = "crunchy-access-portal"
path = "~/Developer/crunchy/crunchy-access-portal"

[[session]]
name = "bridge-docs"
path = "~/Developer/crunchy/bridge-docs"

[[session]]
name = "bridge-raven"
path = "~/Developer/crunchy/bridge-raven"

[[session]]
name = "audio-visual"
path = "~/Developer/projects/audio-visual"

[[session]]
name = "gleam-trpg"
path = "~/Developer/projects/trpg"

[[session]]
name = "lifeos"
path = "~/Developer/laravel/lifeos"

[[session]]
name = "AF"
path = "~/Developer/laravel/af"

[[session]]
name = "whatislaravel"
path = "~/Developer/try-hard/whatislaravel"
