[[session]]
name = "misc"
path = "~/Developer"

[[session]]
name = "dotfiles"
path = "~/.dotfiles"

[[session]]
name = "qmk"
path = "~/qmk_userspace"

[[session]]
name = "wking"
path = "~/Developer/wking"

[[session]]
name = "daw"
path = "~/Developer/daw"

[[session]]
name = "ref-base-ui"
path = "~/.reference/base-ui"

[[session]]
name = "ref-effect"
path = "~/.reference/effect"

[[session]]
name = "ref-effect-atom"
path = "~/.reference/effect-atom"

[[session]]
name = "ref-everforest"
path = "~/.reference/everforest"

[[session]]
name = "ref-opencode"
path = "~/.reference/opencode"
